# : Manager [[[

[manager]
cwd = { fg = "#efdfe1" }

# Tab
tab_active = { fg = "#541d31", bg = "#ffb1c7", bold = true }
tab_inactive = { fg = "#ffd9e2", bg = "#3a071c" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ffa25b", bg = "#ffa25b" }
marker_cut = { fg = "#ffdcc1", bg = "#ffdcc1" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#efbd93", bg = "#efbd93" }

# Count
count_copied = { fg = "#2e1500", bg = "#ffdcc1" }
count_cut = { fg = "#2e1500", bg = "#ffdcc1" }
count_selected = { fg = "#541d31", bg = "#efbd93" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb1c7" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#541d31", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb1c7", fg = "#541d31", bold = true }
normal_alt  = { bg = "#514346", fg = "#d5c2c5" }

# Select mode
select_main = { bg = "#e3bdc6", fg = "#422931", bold = true }
select_alt  = { bg = "#514346", fg = "#d5c2c5" }

# Unset mode
unset_main = { bg = "#efbd93", fg = "#47290b", bold = true }
unset_alt  = { bg = "#514346", fg = "#d5c2c5" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb1c7", bg = "#413739" }
progress_error = { fg = "#ffb4ab", bg = "#413739" }

# Permissions
permissions_t = { fg = "#b55269" }
permissions_w = { fg = "#cb6d1e" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff8628" }
permissions_s = { fg = "#ff406d" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb1c7" }
active = { fg = "#efbd93", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb1c7" }
value = { fg = "#efdfe1" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb1c7", bg = "#541d31" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb1c7" }
title = {}
hovered = { fg = "#ffdcc1", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413739" }
cand = { fg = "#ffb1c7" }
rest = { fg = "#541d31" }
desc = { fg = "#efdfe1" }
separator = " ▶ "
separator_style = { fg = "#efdfe1" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#efdfe1" }
run = { fg = "#efdfe1" }
footer = { fg = "#422931", bg = "#e3bdc6" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#efbd93" }
title_warn = { fg = "#ffb1c7" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#efdfe1" },
    { name = "*/", fg = "#ffb1c7" },
]

# : ]]]